DROP DATABASE IF EXISTS live_hire_db;
CREATE DATABASE live_hire_db;
USE live_hire_db;

CREATE TABLE coordinator (
  id INTEGER AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(50) NOT NULL,
  organization VARCHAR(50) NOT NULL
);

CREATE TABLE band (
  id INTEGER AUTO_INCREMENT PRIMARY KEY
);
